"""Type stubs for robotexclusionrulesparser package."""

class RobotFileParserLookalike:
    """Parser for robots.txt files."""

    def __init__(self) -> None: ...
    def parse(self, lines: list[str]) -> None: ...
    def is_allowed(self, user_agent: str, url: str) -> bool: ...
